name: Install DOLFINx
description: Install DOLFINx from source

inputs:
  dolfinx:
    description: "Branch of DOLFINx"
    required: false
    default: "main"
  ufl:
    description: "Branch of UFL"
    required: false
    default: "main"
  ffcx:
    description: "Branch of FFCx"
    required: false
    default: "main"
  basix:
    description: "Branch of Basix"
    required: false
    default: "main"
  petsc_dir:
    description: "PETSc Directory"
    required: false
    default: "/usr/local/petsc"
  petsc_arch:
    description: "PETSc Arch"
    required: false
    default: "linux-gnu-real-32"
  build_mode:
    description: "Mode to build Basix and DOLFINx"
    required: false
    default: "Release"
  adios2:
    description: "ADIOS2 version/branch"
    required: false
    default: "default"

runs:
  using: composite

  steps:
    - name: Get Basix
      uses: actions/checkout@v4
      with:
        path: ./basix
        repository: FEniCS/basix
        ref: ${{ inputs.basix }}

    - name: Get DOLFINx
      uses: actions/checkout@v4
      with:
        path: ./dolfinx
        repository: FEniCS/dolfinx
        ref: ${{ inputs.dolfinx }}

    - name: Install pybind11
      shell: bash -el {0}
      run: python3 -m pip install pybind11

    - name: Install UFL, Basix, FFCx
      shell: bash -el {0}
      run: |
        cmake -G Ninja -B build-basix -DCMAKE_BUILD_TYPE="Release" -S ./basix/cpp/
        cmake --build build-basix --parallel 2
        cmake --install build-basix
        python3 -m pip  -v install --check-build-dependencies --config-settings=build-dir="build-basix-python" --config-settings=cmake.build-type=${{ inputs.build_mode }}  --config-settings=install.strip=false --no-build-isolation -e ./basix/python
        python3 -m pip install git+https://github.com/FEniCS/ufl.git@${{ inputs.ufl }}
        python3 -m pip install git+https://github.com/FEniCS/ffcx.git@${{ inputs.ffcx }}

    - name: Install adios2
      if: ${{ inputs.adios2 != 'default' }}
      shell: bash -el {0}
      run: |
        git clone --branch=${{ inputs.adios2 }} --single-branch https://github.com/ornladios/ADIOS2.git adios2
        cmake -G Ninja -DADIOS2_USE_HDF5=on -DCMAKE_INSTALL_PYTHONDIR=/usr/local/lib/ -DADIOS2_USE_Fortran=off -DBUILD_TESTING=off -DADIOS2_BUILD_EXAMPLES=off -DADIOS2_USE_ZeroMQ=off -B build-dir-adios2 -S ./adios2
        cmake -G Ninja -B build-dir-adios2 -DCMAKE_BUILD_TYPE="Release" -S ./adios2/
        cmake --build build-dir-adios2 --parallel 2
        cmake --install build-dir-adios2

    - name: Configure C++ (DOLFINx)
      shell: bash -el {0}
      run: PETSC_DIR=${{ inputs.petsc_dir }} PETSC_ARCH=${{ inputs.petsc_arch }} cmake -G Ninja -DCMAKE_BUILD_TYPE=${{ inputs.build_mode }} -B build-dolfinx -S ./dolfinx/cpp/

    - name: Build and install C++ library (dolfinx)
      shell: bash -el {0}
      run: |
        cmake --build build-dolfinx
        cmake --install build-dolfinx

    - name: Build Python interface (DOLFINx)
      shell: bash -el {0}
      run: PETSC_DIR=${{ inputs.petsc_dir }} PETSC_ARCH=${{ inputs.petsc_arch }} python3 -m pip  -v install --check-build-dependencies --config-settings=build-dir="build-dolfinx-python" --config-settings=cmake.build-type=${{ inputs.build_mode }}  --config-settings=install.strip=false --no-build-isolation -e  ./dolfinx/python/
